# Generated by Django 4.2.3 on 2023-12-17 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPublishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.IntegerField(blank=True, null=True, verbose_name='id_group')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentário')),
                ('year_publication', models.DateTimeField(auto_now_add=True, verbose_name='Ano de Publicação')),
                ('quant_like', models.IntegerField(blank=True, default=0, verbose_name='Curtidas')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.chatpublishers')),
            ],
        ),
    ]
