# Generated by Django 4.2.3 on 2023-07-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Nome do Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Nome do Livro')),
                ('cape', models.ImageField(unique=True, upload_to='book/', verbose_name='Capa do Livro')),
                ('sinopse', models.TextField(verbose_name='Sinopse do Livro')),
                ('year_publication', models.DateTimeField(verbose_name='Ano de Publicação')),
                ('book', models.FileField(unique=True, upload_to='book/', verbose_name='Livro')),
                ('quant_like', models.IntegerField(blank=True, default=0, verbose_name='Curtidas')),
                ('quant_downloads', models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Downloads')),
                ('author', models.ManyToManyField(to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=20, unique=True, verbose_name='Gênero')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, verbose_name='like')),
                ('author', models.IntegerField(blank=True, verbose_name='id_user')),
            ],
        ),
        migrations.CreateModel(
            name='Favority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='gender',
            field=models.ManyToManyField(to='books.gender'),
        ),
    ]
