# Generated by Django 4.2.3 on 2023-07-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_publication',
            field=models.DateField(verbose_name='Ano de Publicação'),
        ),
    ]
