# Generated by Django 4.2 on 2023-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_like', models.IntegerField(blank=True, verbose_name='id_like')),
                ('id_user', models.IntegerField(blank=True, verbose_name='id_user')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='quant_like',
            field=models.IntegerField(blank=True, default=0, verbose_name='Curtidas'),
        ),
    ]
