# Generated by Django 4.2 on 2023-06-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_favority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favority',
            name='author',
        ),
        migrations.AddField(
            model_name='favority',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.favority'),
        ),
    ]
