# Generated by Django 4.2 on 2023-06-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_like_book_quant_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quant_downloads',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantidade de Downloads'),
        ),
    ]
