# Generated by Django 4.2 on 2023-06-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_quant_downloads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='id_user',
            new_name='author',
        ),
    ]
