# Generated by Django 4.2 on 2023-06-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_favority_book_alter_favority_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favority',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book', unique=True),
        ),
    ]
