# Generated by Django 4.2 on 2023-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_id_user_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='id_like',
        ),
        migrations.AddField(
            model_name='like',
            name='like',
            field=models.IntegerField(blank=True, default=1, verbose_name='like'),
            preserve_default=False,
        ),
    ]
