# Generated by Django 4.2 on 2023-06-15 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.IntegerField(blank=True, null=True, verbose_name='id_book')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentário')),
                ('response', models.CharField(blank=True, max_length=250, null=True, verbose_name='Responder Comentário')),
                ('id_response', models.IntegerField(blank=True, null=True, verbose_name='id_response')),
                ('year_publication', models.DateTimeField(auto_now_add=True, verbose_name='Ano de Publicação')),
                ('quant_like', models.IntegerField(blank=True, default=0, verbose_name='Curtidas')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
