# Generated by Django 4.2 on 2023-06-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.ImageField(blank=True, default='perfil/img.png', null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
