# Generated by Django 4.2 on 2023-06-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.ImageField(blank=True, default='not_user.jpg', null=True, upload_to='perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
